// src/app/components/layout/footer.tsx
import Link from "next/link";

export default function Footer() {
  return (
    <footer className="bg-secondary grid place-items-center gap-2 py-6 mt-4">
      <p className="text-xl">&copy;dgputt</p>
      <div className="flex gap-3">
        <a
          href="https://www.instagram.com/dgputt/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img src="/images/ig.png" alt="instagram" width={32} height={32} />
        </a>
        <a
          href="https://www.facebook.com/dgputt/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img src="/images/fb.png" alt="facebook" width={32} height={32} />
        </a>
      </div>
      <Link href="/privacy-policy">Privacy Policy</Link>
    </footer>
  );
}

// src/components/Footer.svelte
<footer>
    <p>©dgputt</p>
    <div class="social-media-links">
        <a href="https://www.instagram.com/dgputt/" target="_blank">
            <img src="/images/ig.png" alt="instagram" />
        </a>
        <a href="https://www.facebook.com/dgputt/" target="_blank">
            <img src="/images/fb.png" alt="facebook" />
        </a>
    </div>
    <a href="#/privacy-policy">
        Privacy Policy
    </a>    
</footer>

<style>
	footer {
		padding: 1rem;
	}
	.social-media-links img {
		width: 2rem;
	}
    
    p {
        font-size: 1.25rem;
    }
</style>
